Instead of an empty crate, give a compile error when not on Windows
Previously, programs trying to use winapi on other targets would see
errors like this:

```
failed to resolve: could not find um in winapi
... many other related errors ...
```

Now, they'll see errors like this:

```
  --- stderr
  error: winapi is only supported on Windows platforms
  help: if your application is multi-platform, use `[target.'cfg(windows)'.dependencies] winapi = "..."`
  help: if your application is only supported on Windows, use `--target x86_64-pc-windows-gnu` or some other windows platform
```

This is a breaking change. The reason for this change is two-fold:

1. For programs intending to use winapi, it gives them a much better
error message telling them how to fix the error.
2. For programs that don't need winapi, it forces them to remove it from
dependencies, decreasing their compile times.